# Generated by Django 6.1 on 2026-08-21 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('material_type', models.CharField(choices=[('file', 'Файл / Документ'), ('image', 'Зображення'), ('youtube', 'YouTube Відео'), ('link', 'Зовнішнє посилання')], max_length=10, verbose_name='Тип матеріалу')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/files/', verbose_name='Файл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/images/', verbose_name='Зображення')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Посилання / YouTube URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
